# Change these first
owner: kliang-pptk # Your GitHub organization
repo: status # The name of this repository

sites:
  - name: PPTK.ai Website
    url: https://pptk.ai

status-website:
  # Remove the custom domain line since we don't have one yet
  # Uncomment the baseUrl line and add your repo name
  baseUrl: /status
  logoUrl: https://pptk.ai/favicon.ico
  name: PPTK.ai Status
  introTitle: "**PPTK.ai** System Status"
  introMessage: Live status monitoring for PPTK.ai services. Check here for real-time updates on system availability.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: PPTK.ai
      href: https://pptk.ai

# This configuration will monitor https://pptk.ai every 5 minutes
